/**
 * Base de bairros de Campo Grande MS.
 *
 * Fonte: divisão oficial da PLANURB em 7 regiões urbanas (ver
 * `docs/bairros-campo-grande.md` para a procedência de cada lista).
 *
 * Decisões registradas (pedidos do dono em 16/08/2026):
 * - "Los Angeles" e "Aquários" NÃO entram na base.
 * - "Altos da Afonso Pena" entra mesmo não sendo bairro oficial da PLANURB
 *   (`oficialPlanurb: false`) — é termo de busca forte no alto padrão.
 * - "Parque dos Poderes" é alias do bairro oficial "Veraneio".
 *
 * `tier` orienta a ordem de publicação das landings e o tom da copy:
 *   1 = alto padrão / prioridade máxima para a Nobre Cor
 *   2 = classe média-alta, bairros consolidados, boa demanda
 *   3 = demais bairros (cobertura de cauda longa)
 *
 * `aliases` alimenta busca interna e variações de palavra-chave. `pontosReferencia`
 * é usado na copy hiperlocal — só preencher com o que é REAL. Bairro sem ponto de
 * referência conhecido fica com array vazio e a página omite o bloco (nunca inventar).
 */

import { REGIOES_URBANAS } from './regioes'

export interface Bairro {
  slug: string
  nome: string
  /** Nome curto para o <title>, quando o completo estoura os 60 chars do Google. */
  nomeSeo?: string
  /** slug da região urbana (ver `regioes.ts`) */
  regiao: string
  tier: 1 | 2 | 3
  /** false = área conhecida por busca, mas não é bairro na divisão oficial */
  oficialPlanurb: boolean
  /** Perfil de imóvel predominante — orienta o serviço em destaque na landing. */
  perfil: string
  aliases: string[]
  pontosReferencia: string[]
  /**
   * Contexto hiperlocal: como o perfil de imóvel do bairro muda a EXECUÇÃO da
   * obra. É o conteúdo único que impede thin content na página do bairro.
   *
   * Escrever só o que é verificável ou o que decorre do perfil do bairro.
   * Nunca inventar condomínio, rua ou obra realizada (ver .claude/rules/conteudo.md).
   */
  contexto?: string[]
  /**
   * true = a copy hiperlocal já foi escrita e revisada. O gate
   * `check:thin-content` só cobra as páginas marcadas como revisadas, e reporta
   * quantas ainda faltam. Bairro novo nasce false.
   */
  copyRevisada: boolean
}

export const BAIRROS: Bairro[] = [
  // ─────────────────────────────────────────── REGIÃO URBANA DO PROSA (nobre)
  {
    slug: 'chacara-cachoeira',
    nome: 'Chácara Cachoeira',
    regiao: 'prosa',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Casas e condomínios de alto padrão, lotes amplos, arquitetura autoral',
    aliases: ['chacara cachoeira', 'chácara cachoeira campo grande'],
    pontosReferencia: ['Avenida Afonso Pena', 'Parque das Nações Indígenas', 'Shopping Campo Grande'],
    contexto: [
      'A Chácara Cachoeira concentra o maior padrão construtivo de Campo Grande: casas em lote amplo, projeto de arquitetura assinado e acabamento que é conferido de perto. Aqui a pintura raramente é só trocar a cor. O que se contrata é nivelamento de parede, recorte perfeito e cor especificada pelo arquiteto, executada exatamente como está no projeto.',
      'Na prática, isso muda o cronograma: a preparação da superfície consome mais dias do que a pintura em si, e a amostra na parede precisa ser aprovada antes de a área toda ser fechada. Iluminação de spot e luz natural rasante são padrão nos projetos do bairro, e as duas revelam qualquer ondulação que uma pintura comum deixaria passar.',
      'A proximidade da Avenida Afonso Pena e do Parque das Nações Indígenas também pesa na logística: combinamos horário de entrega de material e montagem de andaime para não travar a rua nem o acesso da casa.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'caranda-bosque',
    nome: 'Carandá Bosque',
    regiao: 'prosa',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Condomínios horizontais fechados e casas de alto padrão',
    aliases: ['caranda bosque', 'carandá bosque'],
    pontosReferencia: ['Carandá Bosque I', 'Carandá Bosque II', 'Avenida Ministro João Arinos'],
    contexto: [
      'O Carandá Bosque é território de condomínio horizontal fechado, e isso define o jeito de trabalhar. A equipe é cadastrada na portaria antes do primeiro dia, o veículo é identificado, e o horário de obra segue o regimento interno do condomínio, inclusive nas regras de ruído.',
      'As casas do bairro costumam ter área externa generosa: muro, fachada, área gourmet e pergolado entram no mesmo orçamento da parte interna. Isso favorece contratar a casa completa de uma vez, porque a montagem de proteção e de acesso é feita uma única vez em vez de a cada chamado.',
      'Como o Carandá Bosque I e II ficam próximos ao eixo da Avenida Ministro João Arinos, o deslocamento da equipe é curto e permite retorno rápido quando algum material específico precisa ser encomendado no meio da obra.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'santa-fe',
    nome: 'Santa Fé',
    regiao: 'prosa',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Residências de alto padrão e edifícios novos próximos à Afonso Pena',
    aliases: ['santa fe', 'jardim santa fé'],
    pontosReferencia: ['Avenida Afonso Pena', 'Parque das Nações Indígenas'],
    contexto: [
      'O Santa Fé mistura residências de alto padrão com edifícios novos, muitos deles a poucos metros da Avenida Afonso Pena. Essa combinação traz dois tipos de obra bem diferentes: a casa que pede acabamento fino ambiente por ambiente e o apartamento na entrega de chaves, que precisa sair rápido e limpo.',
      'Nos edifícios do bairro, a rotina começa na portaria: cadastro da equipe, uso do elevador de serviço com proteção na cabine e respeito ao horário de obra do condomínio. Nas casas, o foco vai para fachada e muro, que sofrem com o sol direto do lado da Afonso Pena.',
      'A proximidade do Parque das Nações Indígenas significa também mais arborização e, com ela, mais umidade e limo em muro voltado para a sombra. É um ponto que sempre conferimos na visita técnica antes de orçar.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'mata-do-jacinto',
    nome: 'Mata do Jacinto',
    regiao: 'prosa',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Casas de alto padrão e área verde preservada, próximo à UFMS',
    aliases: ['mata do jacinto'],
    pontosReferencia: ['UFMS', 'Avenida Costa e Silva'],
    contexto: [
      'A Mata do Jacinto é um dos bairros mais arborizados da região do Prosa, com casas de alto padrão em ruas de sombra densa e proximidade da UFMS. A arborização é o que dá o charme do bairro e, ao mesmo tempo, o principal desafio técnico da pintura externa.',
      'Muro e fachada voltados para a sombra acumulam limo e mofo com muito mais facilidade do que em bairro aberto. Por isso, aqui o tratamento fungicida antes da tinta não é opcional: pintar por cima do limo devolve o problema em poucos meses, agora empolando a tinta nova.',
      'Nas casas do bairro é comum encontrar madeira aparente em deck, pergolado e portão. Esse tipo de superfície pede stain com proteção UV em vez de verniz comum, e entra no orçamento como item separado da pintura de parede.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'veraneio',
    nome: 'Veraneio (Parque dos Poderes)',
    nomeSeo: 'Veraneio',
    regiao: 'prosa',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Sede do Governo do Estado, condomínios e residências de alto padrão',
    aliases: ['parque dos poderes', 'jardim veraneio', 'veraneio'],
    pontosReferencia: ['Parque dos Poderes', 'Palácio Paranhos', 'Avenida do Poeta'],
    contexto: [
      'O Veraneio abriga o Parque dos Poderes e a sede do Governo do Estado, e o entorno acompanha esse padrão: residências de alto padrão, lotes grandes e muita área verde. É um dos endereços mais procurados de Campo Grande para obra de acabamento fino.',
      'A área verde do Parque dos Poderes influencia diretamente a execução: mais sombra e umidade em muros e fachadas voltados para o parque, o que exige tratamento contra limo antes da tinta e escolha de acrílica com boa resistência à umidade.',
      'A circulação na Avenida do Poeta e no entorno do Palácio Paranhos costuma ter restrição de estacionamento e horário. Combinamos a entrega de material e a montagem de andaime com antecedência para não gerar transtorno de acesso.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'chacara-dos-poderes',
    nome: 'Chácara dos Poderes',
    regiao: 'prosa',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Chácaras urbanas e casas de alto padrão em lotes grandes',
    aliases: ['chacara dos poderes', 'chácara dos poderes'],
    pontosReferencia: ['Parque dos Poderes', 'Avenida do Poeta'],
    contexto: [
      'A Chácara dos Poderes reúne chácaras urbanas e casas em lotes grandes, vizinha ao Parque dos Poderes. O metro quadrado de área externa costuma superar bastante o interno, o que inverte a lógica do orçamento em relação a um apartamento.',
      'Aqui o peso está no muro de divisa, na fachada e nas áreas cobertas de lazer. São superfícies expostas ao sol o ano inteiro e à chuva concentrada do verão de Campo Grande, o que torna o fundo preparador e a tinta acrílica com proteção UV a diferença entre repintar em poucos anos ou em muitos.',
      'Lotes grandes também significam acesso mais fácil para andaime e equipamento, o que reduz o tempo de montagem e permite tocar fachada e muro em paralelo com a parte interna.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'novos-estados',
    nome: 'Novos Estados',
    regiao: 'prosa',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Residências consolidadas de bom padrão e edifícios novos',
    aliases: ['novos estados'],
    pontosReferencia: ['Avenida Mato Grosso', 'Avenida Ceará'],
    contexto: [
      'O Novos Estados é um bairro residencial consolidado do Prosa, com casas estabelecidas e edifícios novos convivendo na mesma rua. Boa parte da demanda ali é de repintura: imóvel que já teve pintura antes e agora precisa de recuperação, não de acabamento do zero.',
      'Repintura é o serviço que mais exige diagnóstico antes do orçamento. A tinta antiga pode estar firme (e aí basta preparar e pintar) ou pode estar descolando por falta de fundo na obra anterior, e nesse caso precisa ser removida nos trechos comprometidos. Fazemos esse teste na visita, não no meio da obra.',
      'A localização entre a Avenida Mato Grosso e a Avenida Ceará facilita o acesso da equipe e a reposição de material sem parar a frente de trabalho.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'autonomista',
    nome: 'Autonomista',
    regiao: 'prosa',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Bairro residencial valorizado, casas e prédios de médio e alto padrão',
    aliases: ['autonomista'],
    pontosReferencia: ['Avenida Mato Grosso'],
    contexto: [
      'O Autonomista é um bairro residencial valorizado do Prosa, com mistura de casas consolidadas e prédios de médio e alto padrão. Essa mistura gera dois perfis de obra na mesma rua: a casa que contrata a pintura completa e o apartamento que pinta ambiente por ambiente.',
      'Nos prédios do bairro, o ponto de atenção é sempre o regimento do condomínio: horário permitido, dias liberados e uso do elevador de serviço. Conferimos isso antes de agendar, porque obra fora da regra gera multa para o morador.',
      'Nas casas, a demanda mais comum é fachada e muro voltados para a Avenida Mato Grosso, que pegam poeira e fuligem de via movimentada. A lavagem antes da tinta é o que faz a pintura durar nesses casos.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'noroeste',
    nome: 'Noroeste',
    regiao: 'prosa',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residências consolidadas e comércio de bairro',
    aliases: ['noroeste'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'margarida',
    nome: 'Margarida',
    regiao: 'prosa',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado, casas térreas e sobrados',
    aliases: ['margarida', 'jardim margarida'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'estrela-dalva',
    nome: 'Estrela Dalva',
    regiao: 'prosa',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Bairro residencial próximo ao eixo da Avenida Mato Grosso',
    aliases: ['estrela dalva', "estrela d'alva"],
    pontosReferencia: [],
    copyRevisada: false,
  },

  // ───────────────────────────────────────────── ÁREA DE ALTO PADRÃO (não oficial)
  {
    slug: 'altos-da-afonso-pena',
    nome: 'Altos da Afonso Pena',
    regiao: 'prosa',
    tier: 1,
    oficialPlanurb: false,
    perfil:
      'Faixa nobre ao longo da Avenida Afonso Pena, edifícios de alto padrão, coberturas e casas de arquitetura assinada',
    aliases: ['altos da afonso pena', 'afonso pena alto padrao', 'avenida afonso pena'],
    pontosReferencia: [
      'Avenida Afonso Pena',
      'Parque das Nações Indígenas',
      'Shopping Campo Grande',
      'Praça do Rádio Clube',
    ],
    contexto: [
      'Os Altos da Afonso Pena concentram edifícios altos, coberturas e casas de arquitetura assinada ao longo da avenida mais movimentada da cidade. É um trecho onde o acabamento é conferido no detalhe e onde a obra precisa ser discreta.',
      'Em edifício de alto padrão, o cuidado começa fora do apartamento: proteção do elevador de serviço, zero respingo em hall e corredor, e equipe identificada e cadastrada na portaria. A área comum precisa estar impecável ao fim de cada dia, não só o apartamento em obra.',
      'Nas coberturas, entra ainda a parte externa: laje exposta, platibanda e área de lazer, superfícies que pedem impermeabilização antes da pintura. Fazer o contrário significa jogar fora a pintura nova na primeira estação de chuva.',
      'A Afonso Pena tem trânsito intenso e restrição de parada em vários trechos. Programamos entrega de material e montagem de acesso em horário de menor fluxo, combinado com você e com a administração do prédio.',
    ],
    copyRevisada: true,
  },

  // ────────────────────────────────────────── REGIÃO URBANA DO CENTRO
  {
    slug: 'jardim-dos-estados',
    nome: 'Jardim dos Estados',
    regiao: 'centro',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'O bairro residencial mais tradicional e valorizado da capital',
    aliases: ['jardim dos estados'],
    pontosReferencia: ['Avenida Afonso Pena', 'Praça dos Imigrantes', 'Avenida Mato Grosso'],
    contexto: [
      'O Jardim dos Estados é o bairro residencial mais tradicional de Campo Grande, com casas estabelecidas há décadas e arborização madura. Essa idade dos imóveis define o tipo de trabalho: aqui quase toda obra é recuperação, não pintura de imóvel novo.',
      'Parede com décadas de camadas de tinta pede diagnóstico antes de qualquer orçamento. É comum encontrar tinta antiga sem aderência, massa corrida aplicada em área externa onde deveria ter ido acrílica e trincas de acomodação que precisam ser tratadas, e não apenas cobertas.',
      'A arborização madura das ruas do bairro traz sombra constante em muros e fachadas, com o mofo que vem junto. O tratamento fungicida antes da tinta é etapa obrigatória nas obras do Jardim dos Estados.',
      'A proximidade da Avenida Afonso Pena e da Avenida Mato Grosso facilita o acesso, mas exige combinar horário para entrega de material sem travar a via.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'itanhanga',
    nome: 'Itanhangá',
    regiao: 'centro',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Itanhangá Park, casas de alto padrão em área arborizada',
    aliases: ['itanhanga', 'itanhangá park'],
    pontosReferencia: ['Itanhangá Park', 'Avenida Afonso Pena'],
    contexto: [
      'O Itanhangá Park é um endereço residencial de alto padrão da região central, com casas em terreno amplo e forte presença de área verde. O perfil de obra ali é o de acabamento fino: parede plana, recorte perfeito e cor definida em projeto.',
      'A área verde do bairro traz o mesmo ponto de atenção de toda região arborizada de Campo Grande: superfícies externas na sombra acumulam limo, e tinta aplicada sobre limo descola. Lavagem e tratamento fungicida entram no orçamento como etapa, não como cortesia.',
      'Terreno amplo facilita a logística de andaime e permite tocar a fachada e a parte interna em paralelo, o que encurta o cronograma total da obra.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'monte-libano',
    nome: 'Monte Líbano',
    regiao: 'centro',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Jardim Monte Líbano, residências de alto padrão e edifícios novos',
    aliases: ['monte libano', 'jardim monte líbano'],
    pontosReferencia: ['Avenida Afonso Pena'],
    contexto: [
      'O Jardim Monte Líbano combina residências de alto padrão e edifícios novos, próximo ao eixo da Avenida Afonso Pena. A demanda se divide entre acabamento fino em casa e pintura de apartamento na entrega de chaves.',
      'Em apartamento novo, a parede vem do construtor com massa de obra e nem sempre nivelada. Vale medir a superfície com luz rasante antes de pintar: corrigir agora custa muito menos do que descobrir a ondulação depois, com a mobília já dentro.',
      'Nas casas do bairro, fachada e muro voltados para a Afonso Pena pegam sol direto e poeira de via movimentada. É o cenário que mais exige fundo preparador e tinta acrílica de linha superior.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'centro',
    nome: 'Centro',
    regiao: 'centro',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Prédios comerciais, edifícios residenciais antigos e fachadas históricas',
    aliases: ['centro campo grande', 'centro'],
    pontosReferencia: ['Rua 14 de Julho', 'Praça Ary Coelho', 'Mercadão Municipal', 'Avenida Afonso Pena'],
    contexto: [
      'O Centro de Campo Grande é o cenário mais técnico da cidade para pintura: edifícios comerciais e residenciais antigos, fachadas com décadas de camadas sobrepostas e prédios que não podem parar de funcionar durante a obra.',
      'Em ponto comercial da Rua 14 de Julho e do entorno da Praça Ary Coelho, cada dia fechado é prejuízo. Por isso trabalhamos fora do horário de funcionamento, com o espaço limpo e liberado na abertura do dia seguinte.',
      'Nas fachadas antigas, o trabalho começa muito antes da tinta: lavagem, remoção de tinta solta, tratamento de trinca e fundo preparador. Fachada de prédio no Centro pinta uma vez a cada muitos anos, e é a preparação que define se esse intervalo vai ser longo ou curto.',
      'A circulação intensa da região exige sinalização e isolamento da calçada durante o trabalho em altura, combinados previamente com o síndico ou com o responsável pelo ponto.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'sao-francisco',
    nome: 'São Francisco',
    regiao: 'centro',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'O bairro mais populoso da região central, misto residencial e comercial',
    aliases: ['sao francisco', 'são francisco'],
    pontosReferencia: ['Avenida Fernando Corrêa da Costa'],
    copyRevisada: false,
  },
  {
    slug: 'amambai',
    nome: 'Amambaí',
    regiao: 'centro',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'O bairro mais antigo de Campo Grande, casas históricas e comércio',
    aliases: ['amambai', 'amambaí'],
    pontosReferencia: ['Rua Bahia', 'Avenida Calógeras'],
    copyRevisada: false,
  },
  {
    slug: 'cruzeiro',
    nome: 'Cruzeiro',
    regiao: 'centro',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado próximo ao centro',
    aliases: ['cruzeiro'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'bela-vista',
    nome: 'Bela Vista',
    regiao: 'centro',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Bairro pequeno e tranquilo colado ao centro',
    aliases: ['bela vista'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'planalto',
    nome: 'Planalto',
    regiao: 'centro',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado com comércio de bairro',
    aliases: ['planalto'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'cabreuva',
    nome: 'Cabreúva',
    regiao: 'centro',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial tradicional próximo ao centro',
    aliases: ['cabreuva', 'cabreúva'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'sao-bento',
    nome: 'São Bento',
    regiao: 'centro',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado na área central',
    aliases: ['sao bento', 'são bento'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'gloria',
    nome: 'Glória',
    regiao: 'centro',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Vila Glória, residencial tradicional e comércio local',
    aliases: ['gloria', 'vila glória'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'carvalho',
    nome: 'Carvalho',
    regiao: 'centro',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial de porte pequeno na região central',
    aliases: ['carvalho'],
    pontosReferencia: [],
    copyRevisada: false,
  },

  // ────────────────────────────────────────── REGIÃO URBANA DO BANDEIRA
  {
    slug: 'vilas-boas',
    nome: 'Vilas Boas',
    regiao: 'bandeira',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Condomínios fechados e casas de alto padrão',
    aliases: ['vilas boas', 'vilasboas'],
    pontosReferencia: ['Avenida Ministro João Arinos'],
    contexto: [
      'O Vilas Boas é bairro de condomínio fechado e casas de alto padrão na região do Bandeira. Como em todo condomínio, a obra começa pelo regimento: cadastro da equipe na portaria, veículo identificado e horário de trabalho dentro da regra da administração.',
      'As casas do bairro costumam ter área externa relevante (muro, fachada, área de lazer), o que faz do contrato completo a opção mais econômica: uma montagem de proteção e de acesso atende todas as frentes.',
      'A proximidade da Avenida Ministro João Arinos dá acesso rápido para a equipe e para reposição de material, o que ajuda a manter o cronograma quando surge um item extra no meio da obra.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'rita-vieira',
    nome: 'Rita Vieira',
    regiao: 'bandeira',
    tier: 1,
    oficialPlanurb: true,
    perfil: 'Condomínios horizontais e residências de alto padrão em expansão',
    aliases: ['rita vieira', 'royal park'],
    pontosReferencia: ['Avenida Guaicurus'],
    contexto: [
      'O Rita Vieira é uma das áreas de maior expansão de alto padrão de Campo Grande, com condomínios horizontais e casas novas entregues nos últimos anos. Boa parte da demanda é de imóvel recém-entregue, e não de repintura.',
      'Imóvel novo tem uma armadilha específica: a parede vem com massa de obra e ainda em processo de acomodação. Pintar cedo demais, antes de a alvenaria estabilizar, faz aparecer trinca fina no acabamento novo. Avaliamos isso na visita e orientamos com franqueza quando vale esperar.',
      'Em condomínio horizontal, o acesso de material e a montagem de andaime seguem as regras da administração, e a equipe é cadastrada antes do primeiro dia. O entorno da Avenida Guaicurus facilita o deslocamento.',
    ],
    copyRevisada: true,
  },
  {
    slug: 'tiradentes',
    nome: 'Tiradentes',
    regiao: 'bandeira',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Bairro residencial de grande porte com forte verticalização recente',
    aliases: ['tiradentes'],
    pontosReferencia: ['Avenida Ministro João Arinos'],
    copyRevisada: false,
  },
  {
    slug: 'universitario',
    nome: 'Universitário',
    regiao: 'bandeira',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Apartamentos e residências próximos às universidades',
    aliases: ['universitario', 'universitário'],
    pontosReferencia: ['UCDB', 'Avenida Ceará'],
    copyRevisada: false,
  },
  {
    slug: 'tv-morena',
    nome: 'TV Morena',
    regiao: 'bandeira',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado de bom padrão',
    aliases: ['tv morena'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'jardim-paulista',
    nome: 'Jardim Paulista',
    regiao: 'bandeira',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado com comércio de bairro',
    aliases: ['jardim paulista'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'moreninha',
    nome: 'Moreninha',
    regiao: 'bandeira',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Conjunto habitacional de grande porte e comércio local',
    aliases: ['moreninha', 'moreninhas'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'sao-lourenco',
    nome: 'São Lourenço',
    regiao: 'bandeira',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial em consolidação',
    aliases: ['sao lourenco', 'são lourenço'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'maria-aparecida-pedrossian',
    nome: 'Maria Aparecida Pedrossian',
    nomeSeo: 'M. A. Pedrossian',
    regiao: 'bandeira',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial de grande extensão ao sudeste',
    aliases: ['maria aparecida pedrossian', 'mario covas'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'carlota',
    nome: 'Carlota',
    regiao: 'bandeira',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado',
    aliases: ['carlota', 'jardim carlota'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'dr-albuquerque',
    nome: 'Dr. Albuquerque',
    regiao: 'bandeira',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado com comércio de bairro',
    aliases: ['dr albuquerque', 'doutor albuquerque'],
    pontosReferencia: [],
    copyRevisada: false,
  },

  // ────────────────────────────────────────── REGIÃO URBANA DO SEGREDO
  {
    slug: 'seminario',
    nome: 'Seminário',
    regiao: 'segredo',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial valorizado a norte do centro',
    aliases: ['seminario', 'seminário'],
    pontosReferencia: ['Avenida Duque de Caxias'],
    copyRevisada: false,
  },
  {
    slug: 'monte-castelo',
    nome: 'Monte Castelo',
    regiao: 'segredo',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado com forte comércio de bairro',
    aliases: ['monte castelo'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'coronel-antonino',
    nome: 'Coronel Antonino',
    regiao: 'segredo',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Bairro de grande porte, residencial e comercial',
    aliases: ['coronel antonino'],
    pontosReferencia: ['Avenida Duque de Caxias'],
    copyRevisada: false,
  },
  {
    slug: 'nova-lima',
    nome: 'Nova Lima',
    regiao: 'segredo',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'O bairro mais populoso da região norte, residencial e comércio',
    aliases: ['nova lima'],
    pontosReferencia: ['Avenida Duque de Caxias'],
    copyRevisada: false,
  },
  {
    slug: 'nasser',
    nome: 'Nasser',
    regiao: 'segredo',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Vila Nasser, residencial consolidado',
    aliases: ['nasser', 'vila nasser'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'mata-do-segredo',
    nome: 'Mata do Segredo',
    regiao: 'segredo',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial em expansão junto à área de preservação',
    aliases: ['mata do segredo'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'jose-abrao',
    nome: 'José Abrão',
    regiao: 'segredo',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado',
    aliases: ['jose abrao', 'josé abrão'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'presidente',
    nome: 'Presidente',
    regiao: 'segredo',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado a norte',
    aliases: ['presidente'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'santa-luzia',
    nome: 'Santa Luzia',
    regiao: 'segredo',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado',
    aliases: ['santa luzia'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'marli',
    nome: 'Marli',
    regiao: 'segredo',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial de porte médio',
    aliases: ['marli', 'jardim marli'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'bom-retiro',
    nome: 'Bom Retiro',
    regiao: 'segredo',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial em consolidação',
    aliases: ['bom retiro'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'parque-dos-laranjais',
    nome: 'Parque dos Laranjais',
    regiao: 'segredo',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial de expansão a norte',
    aliases: ['parque dos laranjais'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'dona-dede',
    nome: 'Dona Dedé',
    regiao: 'segredo',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial de porte pequeno',
    aliases: ['dona dede', 'dona dedé'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'cerejeira',
    nome: 'Cerejeira',
    regiao: 'segredo',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Bairro novo da região norte, em consolidação',
    aliases: ['cerejeira', 'cerejeiras'],
    pontosReferencia: [],
    copyRevisada: false,
  },

  // ────────────────────────────────────── REGIÃO URBANA DO ANHANDUIZINHO
  {
    slug: 'aero-rancho',
    nome: 'Aero Rancho',
    regiao: 'anhanduizinho',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'O maior bairro da região sul, com 11 parcelamentos e alto volume residencial',
    aliases: ['aero rancho'],
    pontosReferencia: ['Avenida Gury Marques', 'Shopping Bosque dos Ipês'],
    copyRevisada: false,
  },
  {
    slug: 'jockey-club',
    nome: 'Jockey Club',
    regiao: 'anhanduizinho',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado com comércio de bairro',
    aliases: ['jockey club', 'joquei clube'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'centenario',
    nome: 'Centenário',
    regiao: 'anhanduizinho',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial de grande porte ao sul',
    aliases: ['centenario', 'centenário'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'guanandi',
    nome: 'Guanandi',
    regiao: 'anhanduizinho',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Conjunto habitacional e residências de grande extensão',
    aliases: ['guanandi'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'centro-oeste',
    nome: 'Centro-Oeste',
    regiao: 'anhanduizinho',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado',
    aliases: ['centro oeste', 'centro-oeste'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'parati',
    nome: 'Parati',
    regiao: 'anhanduizinho',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial ao sul da capital',
    aliases: ['parati'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'alves-pereira',
    nome: 'Alves Pereira',
    regiao: 'anhanduizinho',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado',
    aliases: ['alves pereira'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'america',
    nome: 'América',
    regiao: 'anhanduizinho',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial e comércio de bairro',
    aliases: ['america', 'américa'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'jacy',
    nome: 'Jacy',
    regiao: 'anhanduizinho',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial de porte médio',
    aliases: ['jacy'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'lageado',
    nome: 'Lageado',
    regiao: 'anhanduizinho',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial em consolidação',
    aliases: ['lageado'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'pioneiros',
    nome: 'Pioneiros',
    regiao: 'anhanduizinho',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial ao sul',
    aliases: ['pioneiros'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'piratininga',
    nome: 'Piratininga',
    regiao: 'anhanduizinho',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado',
    aliases: ['piratininga'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'taquarussu',
    nome: 'Taquarussu',
    regiao: 'anhanduizinho',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial de expansão ao sul',
    aliases: ['taquarussu'],
    pontosReferencia: [],
    copyRevisada: false,
  },

  // ────────────────────────────────────────── REGIÃO URBANA DA LAGOA
  {
    slug: 'bandeirantes',
    nome: 'Bandeirantes',
    regiao: 'lagoa',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial de grande porte com comércio ativo',
    aliases: ['bandeirantes'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'tijuca',
    nome: 'Tijuca',
    regiao: 'lagoa',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado a sudoeste',
    aliases: ['tijuca'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'sao-conrado',
    nome: 'São Conrado',
    regiao: 'lagoa',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Um dos bairros mais populosos da região sudoeste',
    aliases: ['sao conrado', 'são conrado'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'leblon',
    nome: 'Leblon',
    regiao: 'lagoa',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial de grande porte e comércio de bairro',
    aliases: ['leblon', 'jardim leblon'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'caicara',
    nome: 'Caiçara',
    regiao: 'lagoa',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial tradicional com comércio consolidado',
    aliases: ['caicara', 'caiçara'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'taveiropolis',
    nome: 'Taveirópolis',
    regiao: 'lagoa',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial de grande extensão a oeste',
    aliases: ['taveiropolis', 'taveirópolis'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'uniao',
    nome: 'União',
    regiao: 'lagoa',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado',
    aliases: ['uniao', 'união'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'coophavila-ii',
    nome: 'Coophavila II',
    regiao: 'lagoa',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Conjunto habitacional consolidado',
    aliases: ['coophavila', 'coophavila 2', 'coophavila ii'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'taruma',
    nome: 'Tarumã',
    regiao: 'lagoa',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial de porte médio',
    aliases: ['taruma', 'tarumã'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'caioba',
    nome: 'Caiobá',
    regiao: 'lagoa',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial em consolidação',
    aliases: ['caioba', 'caiobá'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'batistao',
    nome: 'Batistão',
    regiao: 'lagoa',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado a sudoeste',
    aliases: ['batistao', 'batistão'],
    pontosReferencia: [],
    copyRevisada: false,
  },

  // ────────────────────────────────────────── REGIÃO URBANA DO IMBIRUSSU
  {
    slug: 'santo-amaro',
    nome: 'Santo Amaro',
    regiao: 'imbirussu',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado a oeste',
    aliases: ['santo amaro'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'santo-antonio',
    nome: 'Santo Antônio',
    regiao: 'imbirussu',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial e comércio de bairro',
    aliases: ['santo antonio', 'santo antônio'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'nova-campo-grande',
    nome: 'Nova Campo Grande',
    regiao: 'imbirussu',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Residencial de grande porte a oeste',
    aliases: ['nova campo grande'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'popular',
    nome: 'Popular',
    regiao: 'imbirussu',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial tradicional',
    aliases: ['popular', 'vila popular'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'panama',
    nome: 'Panamá',
    regiao: 'imbirussu',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Residencial consolidado',
    aliases: ['panama', 'panamá'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'sobrinho',
    nome: 'Sobrinho',
    regiao: 'imbirussu',
    tier: 3,
    oficialPlanurb: true,
    perfil: 'Vila Sobrinho, residencial consolidado',
    aliases: ['sobrinho', 'vila sobrinho'],
    pontosReferencia: [],
    copyRevisada: false,
  },
  {
    slug: 'nucleo-industrial',
    nome: 'Núcleo Industrial',
    regiao: 'imbirussu',
    tier: 2,
    oficialPlanurb: true,
    perfil: 'Galpões, indústrias e área logística, demanda de epóxi e demarcação de piso',
    aliases: ['nucleo industrial', 'núcleo industrial'],
    pontosReferencia: ['BR-262', 'Avenida Gunter Hans'],
    copyRevisada: false,
  },
]

/** Bairros que NÃO entram na base, por decisão do dono. Documentado para não voltarem. */
export const BAIRROS_EXCLUIDOS = ['Los Angeles', 'Aquários'] as const

export function getBairro(slug: string): Bairro | undefined {
  return BAIRROS.find((b) => b.slug === slug)
}

export function getBairrosPorRegiao(regiaoSlug: string): Bairro[] {
  return BAIRROS.filter((b) => b.regiao === regiaoSlug).sort((a, b) =>
    a.nome.localeCompare(b.nome, 'pt-BR')
  )
}

export function getBairrosPorTier(tier: 1 | 2 | 3): Bairro[] {
  return BAIRROS.filter((b) => b.tier === tier)
}

/** Bairros prioritários para a Nobre Cor (alto padrão). */
export const BAIRROS_PRIORITARIOS = BAIRROS.filter((b) => b.tier === 1)

/** Agrupamento pronto para a página /bairros, na ordem das regiões urbanas. */
export function getBairrosAgrupados() {
  return REGIOES_URBANAS.map((regiao) => ({
    regiao,
    bairros: getBairrosPorRegiao(regiao.slug),
  }))
}

export const TOTAL_BAIRROS = BAIRROS.length
